### ISSUE TITLE
Не появляется кнопка скачивания

### ISSUE THREAD

**Issue by vovanmozg** [KiberInfinity/vk_stuff#1]
Попробовал поставить скрипт по инструкции
http://vkopt.net/forum/showthread.php?t=5508

TamperMonkey и скрипт установились. На странице аудизаписей TamperMonkey показывает, что AuViDL [vkopt module] выполнился 2 раза.

В консоли вижу:
![image](https://user-images.githubusercontent.com/2217466/55095657-903bd680-50c9-11e9-808a-c549326141f8.png)

Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Chrom Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by KiberInfinity** [comment]
А vkopt сам установлен?

**Comment by vovanmozg** [comment]
Его-то я и удалил :). Установил, всё заработало, спасибо!
