### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Venomborn** [KiberInfinity/vk_stuff#2]
Download option no longer appears on files in vk, please fix!

**Comment by KiberInfinity** [comment]
@Venomborn  you should update  vkopt to latest version.

**Comment by Venomborn** [comment]
@KiberInfinity I had attempted to do that before posting, but saw no update anywhere. No update in the google chrome store, no update on the blog. I uninstalled/reinstalled...you name it. Could you be so kind as to link me where I could find this update? I appreciate the response! :)

**Comment by KiberInfinity** [comment]
@Venomborn 
version 3.0.7.14
https://chrome.google.com/webstore/detail/vkopt/hoboppgpbgclpfnjfdidokiilachfcbb
https://github.com/VkOpt/VkOpt/releases/tag/3.0.7.14

**Comment by Venomborn** [comment]
@KiberInfinity thank you very much! All seems to be working as usual now!
