### ISSUE TITLE
Исчезла кнопка скачки музыки

### ISSUE THREAD

**Issue by LeonxPRO** [KiberInfinity/vk_stuff#3]
Добрый день. Исчезла кнопка скачки музыки. Пробовал Ctrl + F5. Пробовал обновить сприпты в TamperMonkey.
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
VkOpt Version 3.0.7.13

Спасибо за расширение!

**Comment by ruslinekzn** [comment]
у меня такая же проблема возникла дня 2-3 назад :(

**Comment by FeelTheLemon** [comment]
тоже самое, только наверное больше недели уже

**Comment by LeonxPRO** [comment]
Сегодня обновился VKOpt, заработала и скачка.
