### ISSUE TITLE
Ошибка получения информации о треке

### ISSUE THREAD

**Issue by ramartynov** [KiberInfinity/vk_stuff#4]
Добрый день.
Часто нарываюсь на ошибку "VK error:  bad_hash":
https://prnt.sc/skaenq
Ошибка появляется при наведении указателя мышки на трек, который был удален по заявлению правообладателя. Такие треки имеют серый текст в наименовании (выделил в предыдущем скрине), а при попытке воспроизвести их появляется это окошко:
https://prnt.sc/skaca6
Получится ли исправить ошибку "VK error:  bad_hash"?

**Comment by ramartynov** [comment]
Забыл сказать, что после этой ошибки не получится скачать ни один трек пока не обновишь страницу.

**Comment by KiberInfinity** [comment]
@ramartynov исправлено
https://github.com/KiberInfinity/vk_stuff/raw/master/auvidl_vkopt.user.js

**Comment by ramartynov** [comment]
Добрый день! Проверил, работает! Спасибо за труды!
